#!/bin/bash
link_src () {
	bot_retorno="$LINE\n"
	bot_retorno+="   🧬🧬 Soporte - OS 🧬🧬 \n  Ubuntu 14 - 16 - 18 - 20 (x64)\n          Debian 7,8,9,10 (x64) \n 𝙍𝙚𝙘𝙤𝙢𝙚𝙣𝙙𝙖𝙙𝙤 𝙐𝙗𝙪𝙣𝙩𝙪 18.04 \n  🪦 Solicita Creditos de tu KEY 🛡️⚔️\n"
	bot_retorno+="(PROXIMAMENTE RUFUS, LATAM)\n"
	bot_retorno+="$LINE\n"
	bot_retorno+="<code>apt-get update;apt-get upgrade -y && wget https://raw.githubusercontent.com/drowkid01/modcgh/main/setup && chmod +x setup && ./setup --ADMcgh</code>\n"
	bot_retorno+="$LINE\n"
	bot_retorno+="$LINE\n"
	bot_retorno+="  🛡️  𝙸𝚗𝚜𝚝𝚊𝚕𝚊𝚍𝚘𝚛  𝙾𝚏𝚒𝚌𝚒𝚊𝚕 $(cat < /etc/SCRIPT/v-local.log) FOR ARM 🛡️ \n"
	bot_retorno+="$LINE\n"
	bot_retorno+="<code>apt-get update;apt-get upgrade -y && wget https://raw.githubusercontent.com/drowkid01/modcgh/main/setup && chmod +x setup && ./setup --ADMcgh</code>\n"
msj_fun
}
